ENTRIES = [
    {"id": "law-civ-99", "category": "law", "doc_type": "act", "topic": "Act",
     "doc_title_ne": "मुलुकी देवानी संहिता, २०७४", "doc_title_en": "Muluki Civil Code, 2074", "section": "99",
     "title_ne": "सम्बन्ध विच्छेद गर्नु अघि अंशबण्डा गर्नु पर्ने", "title_en": "",
     "text_ne": "९९. सम्बन्ध विच्छेद गर्नु अघि अंशबण्डा गर्नु पर्ने : पति पत्नी बीच सम्बन्ध विच्छेद हुँदा पत्नीले अंश पाउनेछ ।",
     "text_en": "", "source_ne": "मुलुकी देवानी संहिता, २०७४, दफा 99", "source_en": "Muluki Civil Code, 2074, Section 99",
     "url": "https://giwmscdnone.gov.np/civil.pdf#page=30",
     "doc_id": "abc1234567", "provision_id": "abc1234567:99", "status": "in_force",
     "enacted_bs": "2074-06-30", "amended_by": [], "consolidated_upto": "2074-06-30"},
    {"id": "law-civ-400", "category": "law", "doc_type": "act", "topic": "Act",
     "doc_title_ne": "मुलुकी देवानी संहिता, २०७४", "doc_title_en": "Muluki Civil Code, 2074", "section": "400",
     "title_ne": "घर बहाल छाड्न सूचना दिनु पर्ने", "title_en": "",
     "text_ne": "४००. घर बहाल : बहालवालाले घर छाड्नु अघि पैंतीस दिनको सूचना दिनु पर्नेछ र धरौटी रकम फिर्ता गर्नु पर्नेछ ।",
     "text_en": "", "source_ne": "मुलुकी देवानी संहिता, २०७४, दफा 400", "source_en": "Muluki Civil Code, 2074, Section 400",
     "url": "https://giwmscdnone.gov.np/civil.pdf#page=120"},
    {"id": "law-crim-173", "category": "law", "doc_type": "act", "topic": "Act",
     "doc_title_ne": "मुलुकी अपराध संहिता, २०७४", "doc_title_en": "Muluki Criminal Code, 2074", "section": "173",
     "title_ne": "बाल विवाह गर्न नहुने", "title_en": "",
     "text_ne": "१७३. बाल विवाह गर्न नहुने : बीस वर्ष नपुगी विवाह गरेमा तीन वर्षसम्म कैद हुनेछ ।",
     "text_en": "", "source_ne": "मुलुकी अपराध संहिता, २०७४, दफा 173", "source_en": "Muluki Criminal Code, 2074, Section 173",
     "url": "https://giwmscdnone.gov.np/crim.pdf#page=70"},
    {"id": "law-crim-173-dup", "category": "law", "doc_type": "other", "topic": "Report",
     "doc_title_ne": "अध्ययन प्रतिवेदन", "doc_title_en": "", "section": None,
     "title_ne": "अध्ययन प्रतिवेदन", "title_en": "",
     "text_ne": "१७३. बाल विवाह गर्न नहुने : बीस वर्ष नपुगी विवाह गरेमा तीन वर्षसम्म कैद हुनेछ ।",
     "text_en": "", "source_ne": "अध्ययन प्रतिवेदन", "source_en": "Study report", "url": "https://lawcommission.gov.np/"},
    {"id": "law-const-11", "category": "law", "doc_type": "constitution", "topic": "Constitution",
     "doc_title_ne": "नेपालको संविधान", "doc_title_en": "Constitution of Nepal", "section": "11",
     "title_ne": "नेपालको नागरिक ठहर्ने", "title_en": "Citizenship",
     "text_ne": "११. नेपालको नागरिक ठहर्ने : वंशजको आधारमा नागरिकता प्राप्त गर्न सकिनेछ ।",
     "text_en": "Citizenship of Nepal may be acquired by descent.",
     "source_ne": "नेपालको संविधान, धारा 11", "source_en": "Constitution of Nepal, Article 11",
     "url": "https://giwmscdnone.gov.np/constitution.pdf#page=5"},
    {"id": "nkp-1", "category": "precedent", "doc_type": "precedent", "topic": "अंश",
     "doc_title_ne": "निर्णय नं. ९१६८ - अंश", "doc_title_en": "", "section": None,
     "title_ne": "निर्णय नं. ९१६८ - अंश", "title_en": "Supreme Court of Nepal, Decision No. 9168",
     "text_ne": "सम्बन्ध विच्छेद हुँदा पत्नीले पतिको सम्पत्तिबाट अंश पाउने । (प्रकरण नं.३)",
     "text_en": "", "source_ne": "ने.का.प. २०७१ अंक ५ नि.नं. ९१६८", "source_en": "NKP 2071, Decision No. 9168",
     "url": "https://nkp.gov.np/full_detail/1"},
    {"id": "law-bill-1", "category": "law", "doc_type": "act", "topic": "Act",
     "doc_title_ne": "बाल विवाह विरुद्ध थप कडा सजाय सम्बन्धमा व्यवस्था गर्न बनेको विधेयक", "doc_title_en": "",
     "section": "1", "title_ne": "संक्षिप्त नाम र प्रारम्भ", "title_en": "",
     "text_ne": "१. यस विधेयकको नाम बाल विवाह विरुद्ध थप कडा सजाय सम्बन्धमा व्यवस्था गर्न बनेको विधेयक रहेको छ । "
                "बाल विवाह गर्नेलाई थप कडा कैद सजाय हुनेछ ।",
     "text_en": "", "source_ne": "बाल विवाह विरुद्ध थप कडा सजाय सम्बन्धमा व्यवस्था गर्न बनेको विधेयक, दफा 1",
     "source_en": "", "url": "https://lawcommission.gov.np/bill.pdf",
     "doc_id": "bill1234567", "provision_id": "bill1234567:1", "status": "bill",
     "enacted_bs": None, "amended_by": [], "consolidated_upto": None},
    # shaped like a real curated entry (backend/app/data/corpus.json): no
    # doc_title_ne, no status field, category=law, curated=True - a bill
    # title only findable in title_ne/source_ne (see docs/PROGRESS.md S3.1)
    {"id": "national-debt-raising-bill-2083-section-2", "category": "law", "doc_type": "other",
     "topic": "Government/Finance Law", "title_en": "Authority to Raise National Debt",
     "title_ne": "राष्ट्र ऋण उठाउन सक्ने", "text_en": "The Government of Nepal is authorized to raise national debt.",
     "text_ne": "नेपाल सरकारले राष्ट्र ऋण उठाउन सक्नेछ।",
     "source_en": "National Debt Raising Bill, 2083", "source_ne": "राष्ट्र ऋण उठाउने विधेयक, २०८३",
     "url": "https://lawcommission.gov.np/", "section": None, "curated": True},
]
